repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.6.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v24.5.0
    hooks:
      - id: ansible-lint
        name: Ansible Lint
        language: python
        additional_dependencies:
          - ansible
        files: provision.yaml
