---
- name: Debian Trixie 
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Add Debian Trixie stable, updates and backports repos
      ansible.builtin.deb822_repository:
        name: debian
        types:
          - deb
          - deb-src
        uris: https://deb.debian.org/debian
        suites:
          - trixie
          - trixie-updates
          - trixie-backports
        components:
          - main
          - contrib
          - non-free
          - non-free-firmware
        signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
      become: true
    - name: Add Debian Trixie security repo
      ansible.builtin.deb822_repository:
        name: debian
        types:
          - deb
          - deb-src
        uris: https://security.debian.org/debian-security
        suites: trixie-security
        components:
          - main
          - contrib
          - non-free
          - non-free-firmware
        signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
      become: true
    - name: update
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        upgrade: dist
      become: true
