---
- name: Firmware and hardware monitoring
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install firmware and hardware monitoring packages
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        name:
          - amd64-microcode
          - firmware-linux
          - lm-sensors
          - lshw
          - nvidia-driver
          - usbutils
      become: true
