---
- name: Games
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install game packages
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        name:
          - mesa-vulkan-drivers
          - mesa-vulkan-drivers:i386
          - libgl1-mesa-dri:i386 
          - libglx-mesa0:i386
          - steam-installer
          - lutris
          - wine
          - wine32
          - wine64
          - fonts-wine
    - name: Install Minecraft package
      ansible.builtin.apt:
        force_apt_get: true
        deb: https://launcher.mojang.com/download/Minecraft.deb
