name: CI

on:
  push:
    branches: dev
  pull_request:
    branches: main

strategy:
  fail-fast: true
  matrix:
    os: ubuntu-latest

defaults:
  run:
    shell: bash -l {0}

permissions:
  contents: read

jobs:
  integration:
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          targets: |
            provision.yaml
